### ISSUE TITLE
Unable to Open Exam

### ISSUE THREAD

**Issue by b0ssdi0s** [gucci-on-fleek/lockdown-browser#48] opened 2024-01-19 02:15 UTC
Lockdown opens properly in the sandbox and you are able to log in and navigate canvas, but once you select an exam it gives you this error message:
"Unable to Open Exam
In order to take a New Quizzes exam with LockDown Browser, you must first use a standard browser (e.g. Chrome, Firefox, etc.) to navigate to the exam. Lockdown Browser will open automatically when you select "Begin."

Select OK now to close LockDown Browser."

Are there any noted solutions to this issue?
Much appreciated!!

**Comment by gucci-on-fleek** [comment] 2024-02-10 13:20
Probably a duplicate of #5/#17/#22.

Yeah, a few schools have their *Browser*s set up this way. Generally, the process is to launch the _Sandbox_ as usual, but when the _Lockdown Browser_ opens, close it. Then still inside the _Sandbox_ launch Edge and sign in to your school's Canvas page. From there, when you click the link to launch the exam, it should open up inside the _Lockdown Browser_.

If that doesn't work, feel free to add a new comment and reopen the issue.

**Closed by gucci-on-fleek** 2024-02-10 13:20 UTC
