### ISSUE TITLE
IMPORTANT: Using new versions of Respondus Lockdown browser does not work

### ISSUE THREAD

**Issue by thedarkcolour** [gucci-on-fleek/lockdown-browser#75] opened 2024-05-07 20:55 UTC
Respondus will work for about 30 seconds into the quiz, then it will kick you out with a warning.

**Comment by mauriciomollard** [comment] 2024-05-08 18:49
so this way is not working anymore ?

**Comment by gucci-on-fleek** [comment] 2024-05-09 23:36
Duplicate of #65.

**Closed by gucci-on-fleek** 2024-05-09 23:36 UTC
