### ISSUE TITLE
Lockdown Browser Account Banned

### ISSUE THREAD

**Issue by iminthis** [gucci-on-fleek/lockdown-browser#70] opened 2024-03-31 22:14 UTC
Well, I just tried messing around with the older versions trying to fix the ban threat from LDB and they completely banned my account on the second try lol. LDB just kicks me out shortly after using it whether I do it legit or through sandbox.

Thought I'd let you guys know if you're feeling experimental too - This is funny

**Comment by MitPatel971997** [comment] 2024-04-01 15:49
Yah, I encountered the same problem even if we are the instance is running inside the sandbox and if we try to exit lockdown its get warning and kicks us out. Now they are more secure I'm still trying to figure that out how its happening.

**Comment by gucci-on-fleek** [comment] 2024-04-13 09:02
Ah, that's unfortunate. I'm going to close this issue as a duplicate of #65; but please, feel free to continue the discussion there. And thanks for the report.

**Closed by gucci-on-fleek** 2024-04-13 09:02 UTC
