### ISSUE TITLE
Respondus Sandbox Assignment Submission Issue

### ISSUE THREAD

**Issue by wabwest10** [gucci-on-fleek/lockdown-browser#50] opened 2024-01-26 14:00 UTC
I recently encountered an issue with the Respondus exam software while using the Sandbox. Initially, everything seemed to go smoothly, with the Sandbox launching correctly, and Respondus working properly during the assignment. However, when the assignment time expired, I couldn't exit the assignment screen where it displayed "0 seconds remaining," even though it should have automatically closed when the assignment time ended. To exit, I had to click on the "submit" button, but doing so resulted in a red error bar appearing at the top of the screen.

I'm concerned about what caused this anomaly and whether it's a serious issue or a bug. I also want to know if the assignment was still submitted correctly.

I would greatly appreciate an urgent response to this problem and any guidance on how to resolve it.

**Comment by DeadFrostt** [comment] 2024-02-07 17:21
was it submitted successfully?

**Comment by gucci-on-fleek** [comment] 2024-02-10 13:49
Duplicate of #47, please direct further questions/comments there.

**Closed by gucci-on-fleek** 2024-02-10 13:49 UTC
